-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity hand_num_nn_thetafYi_rom is 
    generic(
             dwidth     : integer := 32; 
             awidth     : integer := 5; 
             mem_size    : integer := 30
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of hand_num_nn_thetafYi_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "10111101111110010001101100011010", 
    1 => "10111110000111001011100110010000", 
    2 => "00111110110000010100000001111110", 
    3 => "00111111010001011101011101011100", 
    4 => "00111111011001011101111000001111", 
    5 => "10111111000110001111010110000001", 
    6 => "00111111100100101010011110000110", 
    7 => "10111110110100111011011011000111", 
    8 => "00111111110001111100111111111100", 
    9 => "10111110110010100011011001110001", 
    10 => "00111111100011110110110100000110", 
    11 => "10111111011011010110010011010010", 
    12 => "00111111100011101011110110111010", 
    13 => "10111111100010000111011110000100", 
    14 => "10111111000011010001110110101100", 
    15 => "00111110100110000010111110000000", 
    16 => "10111110100001011011010000010011", 
    17 => "00111111011100000110001100010001", 
    18 => "10111110100010010100001010000100", 
    19 => "10111110101000011010010101000100", 
    20 => "00111111100010111111010101111011", 
    21 => "10111111010011010000001101111100", 
    22 => "10111110011100110010100101000010", 
    23 => "00111110101110011101011010001000", 
    24 => "10111011111001010000111000100010", 
    25 => "10111110110111000011001000000000", 
    26 => "00111111011110111010010111101010", 
    27 => "10111111100001100000100101010001", 
    28 => "01000000000110010101010110000001", 
    29 => "00111111111000000000001111111000" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity hand_num_nn_thetafYi is
    generic (
        DataWidth : INTEGER := 32;
        AddressRange : INTEGER := 30;
        AddressWidth : INTEGER := 5);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of hand_num_nn_thetafYi is
    component hand_num_nn_thetafYi_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    hand_num_nn_thetafYi_rom_U :  component hand_num_nn_thetafYi_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


