// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hand_num_nn.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hand_num_nn::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic hand_num_nn::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<113> hand_num_nn::ap_ST_fsm_state1 = "1";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state2 = "10";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state3 = "100";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state4 = "1000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state5 = "10000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state6 = "100000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state7 = "1000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state8 = "10000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state9 = "100000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state10 = "1000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state11 = "10000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state12 = "100000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state70 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state71 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state72 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state73 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state74 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state75 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state76 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state77 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state78 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state79 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state80 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state81 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state82 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state83 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state84 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state85 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state86 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state87 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state88 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state89 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state90 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state91 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state92 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state93 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state94 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state95 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state96 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state97 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state98 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state99 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state100 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state101 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state102 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state103 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state104 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state105 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state106 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state107 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state108 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state109 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state110 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state111 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state112 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<113> hand_num_nn::ap_ST_fsm_state113 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> hand_num_nn::ap_const_lv32_0 = "00000000000000000000000000000000";
const int hand_num_nn::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> hand_num_nn::ap_const_lv32_7 = "111";
const sc_lv<32> hand_num_nn::ap_const_lv32_1B = "11011";
const sc_lv<32> hand_num_nn::ap_const_lv32_2E = "101110";
const sc_lv<32> hand_num_nn::ap_const_lv32_C = "1100";
const sc_lv<32> hand_num_nn::ap_const_lv32_20 = "100000";
const sc_lv<32> hand_num_nn::ap_const_lv32_37 = "110111";
const sc_lv<32> hand_num_nn::ap_const_lv32_12 = "10010";
const sc_lv<32> hand_num_nn::ap_const_lv32_26 = "100110";
const sc_lv<32> hand_num_nn::ap_const_lv32_33 = "110011";
const sc_lv<32> hand_num_nn::ap_const_lv32_1 = "1";
const sc_lv<1> hand_num_nn::ap_const_lv1_0 = "0";
const sc_lv<32> hand_num_nn::ap_const_lv32_2 = "10";
const sc_lv<1> hand_num_nn::ap_const_lv1_1 = "1";
const sc_lv<32> hand_num_nn::ap_const_lv32_3 = "11";
const sc_lv<32> hand_num_nn::ap_const_lv32_4 = "100";
const sc_lv<32> hand_num_nn::ap_const_lv32_D = "1101";
const sc_lv<32> hand_num_nn::ap_const_lv32_13 = "10011";
const sc_lv<32> hand_num_nn::ap_const_lv32_15 = "10101";
const sc_lv<32> hand_num_nn::ap_const_lv32_16 = "10110";
const sc_lv<32> hand_num_nn::ap_const_lv32_17 = "10111";
const sc_lv<32> hand_num_nn::ap_const_lv32_18 = "11000";
const sc_lv<32> hand_num_nn::ap_const_lv32_21 = "100001";
const sc_lv<32> hand_num_nn::ap_const_lv32_27 = "100111";
const sc_lv<32> hand_num_nn::ap_const_lv32_29 = "101001";
const sc_lv<32> hand_num_nn::ap_const_lv32_2A = "101010";
const sc_lv<32> hand_num_nn::ap_const_lv32_38 = "111000";
const sc_lv<32> hand_num_nn::ap_const_lv32_4A = "1001010";
const sc_lv<32> hand_num_nn::ap_const_lv32_50 = "1010000";
const sc_lv<32> hand_num_nn::ap_const_lv32_6F = "1101111";
const sc_lv<4> hand_num_nn::ap_const_lv4_0 = "0000";
const sc_lv<32> hand_num_nn::ap_const_lv32_14 = "10100";
const sc_lv<3> hand_num_nn::ap_const_lv3_0 = "000";
const sc_lv<32> hand_num_nn::ap_const_lv32_28 = "101000";
const sc_lv<5> hand_num_nn::ap_const_lv5_0 = "00000";
const sc_lv<32> hand_num_nn::ap_const_lv32_BEC56142 = "10111110110001010110000101000010";
const sc_lv<32> hand_num_nn::ap_const_lv32_8 = "1000";
const sc_lv<32> hand_num_nn::ap_const_lv32_E = "1110";
const sc_lv<32> hand_num_nn::ap_const_lv32_1C = "11100";
const sc_lv<32> hand_num_nn::ap_const_lv32_22 = "100010";
const sc_lv<32> hand_num_nn::ap_const_lv32_2F = "101111";
const sc_lv<32> hand_num_nn::ap_const_lv32_2B = "101011";
const sc_lv<32> hand_num_nn::ap_const_lv32_70 = "1110000";
const sc_lv<64> hand_num_nn::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<32> hand_num_nn::ap_const_lv32_4B = "1001011";
const sc_lv<32> hand_num_nn::ap_const_lv32_51 = "1010001";
const sc_lv<32> hand_num_nn::ap_const_lv32_39 = "111001";
const sc_lv<4> hand_num_nn::ap_const_lv4_F = "1111";
const sc_lv<4> hand_num_nn::ap_const_lv4_1 = "1";
const sc_lv<3> hand_num_nn::ap_const_lv3_7 = "111";
const sc_lv<3> hand_num_nn::ap_const_lv3_1 = "1";
const sc_lv<32> hand_num_nn::ap_const_lv32_1E = "11110";
const sc_lv<8> hand_num_nn::ap_const_lv8_FF = "11111111";
const sc_lv<23> hand_num_nn::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> hand_num_nn::ap_const_lv5_1E = "11110";
const sc_lv<5> hand_num_nn::ap_const_lv5_1 = "1";
const sc_lv<32> hand_num_nn::ap_const_lv32_80000000 = "10000000000000000000000000000000";
const sc_lv<5> hand_num_nn::ap_const_lv5_4 = "100";
const sc_lv<64> hand_num_nn::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const bool hand_num_nn::ap_const_boolean_1 = true;

hand_num_nn::hand_num_nn(sc_module_name name) : sc_module(name), mVcdFile(0) {
    theta1h1_U = new hand_num_nn_thetabkb("theta1h1_U");
    theta1h1_U->clk(ap_clk);
    theta1h1_U->reset(ap_rst_n_inv);
    theta1h1_U->address0(theta1h1_address0);
    theta1h1_U->ce0(theta1h1_ce0);
    theta1h1_U->q0(theta1h1_q0);
    theta1b2_U = new hand_num_nn_thetacud("theta1b2_U");
    theta1b2_U->clk(ap_clk);
    theta1b2_U->reset(ap_rst_n_inv);
    theta1b2_U->address0(theta1b2_address0);
    theta1b2_U->ce0(theta1b2_ce0);
    theta1b2_U->q0(theta1b2_q0);
    theta2h3_U = new hand_num_nn_thetadEe("theta2h3_U");
    theta2h3_U->clk(ap_clk);
    theta2h3_U->reset(ap_rst_n_inv);
    theta2h3_U->address0(theta2h3_address0);
    theta2h3_U->ce0(theta2h3_ce0);
    theta2h3_U->q0(theta2h3_q0);
    theta2b4_U = new hand_num_nn_thetaeOg("theta2b4_U");
    theta2b4_U->clk(ap_clk);
    theta2b4_U->reset(ap_rst_n_inv);
    theta2b4_U->address0(theta2b4_address0);
    theta2b4_U->ce0(theta2b4_ce0);
    theta2b4_U->q0(theta2b4_q0);
    theta3h5_U = new hand_num_nn_thetafYi("theta3h5_U");
    theta3h5_U->clk(ap_clk);
    theta3h5_U->reset(ap_rst_n_inv);
    theta3h5_U->address0(theta3h5_address0);
    theta3h5_U->ce0(theta3h5_ce0);
    theta3h5_U->q0(theta3h5_q0);
    hand_num_nn_CRTL_BUS_s_axi_U = new hand_num_nn_CRTL_BUS_s_axi<C_S_AXI_CRTL_BUS_ADDR_WIDTH,C_S_AXI_CRTL_BUS_DATA_WIDTH>("hand_num_nn_CRTL_BUS_s_axi_U");
    hand_num_nn_CRTL_BUS_s_axi_U->AWVALID(s_axi_CRTL_BUS_AWVALID);
    hand_num_nn_CRTL_BUS_s_axi_U->AWREADY(s_axi_CRTL_BUS_AWREADY);
    hand_num_nn_CRTL_BUS_s_axi_U->AWADDR(s_axi_CRTL_BUS_AWADDR);
    hand_num_nn_CRTL_BUS_s_axi_U->WVALID(s_axi_CRTL_BUS_WVALID);
    hand_num_nn_CRTL_BUS_s_axi_U->WREADY(s_axi_CRTL_BUS_WREADY);
    hand_num_nn_CRTL_BUS_s_axi_U->WDATA(s_axi_CRTL_BUS_WDATA);
    hand_num_nn_CRTL_BUS_s_axi_U->WSTRB(s_axi_CRTL_BUS_WSTRB);
    hand_num_nn_CRTL_BUS_s_axi_U->ARVALID(s_axi_CRTL_BUS_ARVALID);
    hand_num_nn_CRTL_BUS_s_axi_U->ARREADY(s_axi_CRTL_BUS_ARREADY);
    hand_num_nn_CRTL_BUS_s_axi_U->ARADDR(s_axi_CRTL_BUS_ARADDR);
    hand_num_nn_CRTL_BUS_s_axi_U->RVALID(s_axi_CRTL_BUS_RVALID);
    hand_num_nn_CRTL_BUS_s_axi_U->RREADY(s_axi_CRTL_BUS_RREADY);
    hand_num_nn_CRTL_BUS_s_axi_U->RDATA(s_axi_CRTL_BUS_RDATA);
    hand_num_nn_CRTL_BUS_s_axi_U->RRESP(s_axi_CRTL_BUS_RRESP);
    hand_num_nn_CRTL_BUS_s_axi_U->BVALID(s_axi_CRTL_BUS_BVALID);
    hand_num_nn_CRTL_BUS_s_axi_U->BREADY(s_axi_CRTL_BUS_BREADY);
    hand_num_nn_CRTL_BUS_s_axi_U->BRESP(s_axi_CRTL_BUS_BRESP);
    hand_num_nn_CRTL_BUS_s_axi_U->ACLK(ap_clk);
    hand_num_nn_CRTL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    hand_num_nn_CRTL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    hand_num_nn_CRTL_BUS_s_axi_U->ap_start(ap_start);
    hand_num_nn_CRTL_BUS_s_axi_U->interrupt(interrupt);
    hand_num_nn_CRTL_BUS_s_axi_U->ap_ready(ap_ready);
    hand_num_nn_CRTL_BUS_s_axi_U->ap_done(ap_done);
    hand_num_nn_CRTL_BUS_s_axi_U->ap_idle(ap_idle);
    hand_num_nn_CRTL_BUS_s_axi_U->ap_return(h3_2_fu_312_p1);
    hand_num_nn_CRTL_BUS_s_axi_U->y(y);
    h1_U = new hand_num_nn_h1("h1_U");
    h1_U->clk(ap_clk);
    h1_U->reset(ap_rst_n_inv);
    h1_U->address0(h1_address0);
    h1_U->ce0(h1_ce0);
    h1_U->we0(h1_we0);
    h1_U->d0(h1_d0);
    h1_U->q0(h1_q0);
    h2_U = new hand_num_nn_h2("h2_U");
    h2_U->clk(ap_clk);
    h2_U->reset(ap_rst_n_inv);
    h2_U->address0(h2_address0);
    h2_U->ce0(h2_ce0);
    h2_U->we0(h2_we0);
    h2_U->d0(h2_d0);
    h2_U->q0(h2_q0);
    hand_num_nn_fadd_g8j_U1 = new hand_num_nn_fadd_g8j<1,5,32,32,32>("hand_num_nn_fadd_g8j_U1");
    hand_num_nn_fadd_g8j_U1->clk(ap_clk);
    hand_num_nn_fadd_g8j_U1->reset(ap_rst_n_inv);
    hand_num_nn_fadd_g8j_U1->din0(grp_fu_297_p0);
    hand_num_nn_fadd_g8j_U1->din1(grp_fu_297_p1);
    hand_num_nn_fadd_g8j_U1->ce(ap_var_for_const0);
    hand_num_nn_fadd_g8j_U1->dout(grp_fu_297_p2);
    hand_num_nn_fmul_hbi_U2 = new hand_num_nn_fmul_hbi<1,4,32,32,32>("hand_num_nn_fmul_hbi_U2");
    hand_num_nn_fmul_hbi_U2->clk(ap_clk);
    hand_num_nn_fmul_hbi_U2->reset(ap_rst_n_inv);
    hand_num_nn_fmul_hbi_U2->din0(grp_fu_306_p0);
    hand_num_nn_fmul_hbi_U2->din1(grp_fu_306_p1);
    hand_num_nn_fmul_hbi_U2->ce(ap_var_for_const0);
    hand_num_nn_fmul_hbi_U2->dout(grp_fu_306_p2);
    hand_num_nn_fptruibs_U3 = new hand_num_nn_fptruibs<1,1,64,32>("hand_num_nn_fptruibs_U3");
    hand_num_nn_fptruibs_U3->din0(tmp_12_reg_811);
    hand_num_nn_fptruibs_U3->dout(h3_2_fu_312_p1);
    hand_num_nn_fpextjbC_U4 = new hand_num_nn_fpextjbC<1,1,32,64>("hand_num_nn_fpextjbC_U4");
    hand_num_nn_fpextjbC_U4->din0(tmp_8_fu_315_p0);
    hand_num_nn_fpextjbC_U4->dout(tmp_8_fu_315_p1);
    hand_num_nn_fcmp_kbM_U5 = new hand_num_nn_fcmp_kbM<1,1,32,32,1>("hand_num_nn_fcmp_kbM_U5");
    hand_num_nn_fcmp_kbM_U5->din0(reg_349);
    hand_num_nn_fcmp_kbM_U5->din1(ap_var_for_const1);
    hand_num_nn_fcmp_kbM_U5->opcode(ap_var_for_const2);
    hand_num_nn_fcmp_kbM_U5->dout(grp_fu_318_p2);
    hand_num_nn_dadd_lbW_U6 = new hand_num_nn_dadd_lbW<1,6,64,64,64>("hand_num_nn_dadd_lbW_U6");
    hand_num_nn_dadd_lbW_U6->clk(ap_clk);
    hand_num_nn_dadd_lbW_U6->reset(ap_rst_n_inv);
    hand_num_nn_dadd_lbW_U6->din0(tmp_10_reg_801);
    hand_num_nn_dadd_lbW_U6->din1(ap_var_for_const3);
    hand_num_nn_dadd_lbW_U6->ce(ap_var_for_const0);
    hand_num_nn_dadd_lbW_U6->dout(grp_fu_323_p2);
    hand_num_nn_ddiv_mb6_U7 = new hand_num_nn_ddiv_mb6<1,31,64,64,64>("hand_num_nn_ddiv_mb6_U7");
    hand_num_nn_ddiv_mb6_U7->clk(ap_clk);
    hand_num_nn_ddiv_mb6_U7->reset(ap_rst_n_inv);
    hand_num_nn_ddiv_mb6_U7->din0(ap_var_for_const3);
    hand_num_nn_ddiv_mb6_U7->din1(tmp_11_reg_806);
    hand_num_nn_ddiv_mb6_U7->ce(ap_var_for_const0);
    hand_num_nn_ddiv_mb6_U7->dout(grp_fu_328_p2);
    hand_num_nn_dexp_ncg_U8 = new hand_num_nn_dexp_ncg<1,18,64,64,64>("hand_num_nn_dexp_ncg_U8");
    hand_num_nn_dexp_ncg_U8->clk(ap_clk);
    hand_num_nn_dexp_ncg_U8->reset(ap_rst_n_inv);
    hand_num_nn_dexp_ncg_U8->din0(ap_var_for_const4);
    hand_num_nn_dexp_ncg_U8->din1(tmp_8_reg_796);
    hand_num_nn_dexp_ncg_U8->ce(ap_var_for_const0);
    hand_num_nn_dexp_ncg_U8->dout(grp_fu_333_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_X_Addr_A);
    sensitive << ( X_Addr_A_orig );

    SC_METHOD(thread_X_Addr_A_orig);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_5_fu_420_p1 );

    SC_METHOD(thread_X_Clk_A);
    sensitive << ( ap_clk );

    SC_METHOD(thread_X_Din_A);

    SC_METHOD(thread_X_EN_A);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_X_Rst_A);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_X_WEN_A);

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state112);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state113);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state44);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state47);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state48);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state52);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state57);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state58);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state75);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state76);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state81);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state82);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state113 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_h3_phi_fu_278_p4);
    sensitive << ( h3_reg_274 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state113 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_exitcond1_fu_496_p2);
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( j_1_reg_262 );

    SC_METHOD(thread_exitcond2_fu_475_p2);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( i_1_reg_239 );

    SC_METHOD(thread_exitcond3_fu_376_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_reg_227 );

    SC_METHOD(thread_exitcond4_fu_355_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_204 );

    SC_METHOD(thread_exitcond_fu_603_p2);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( i_2_reg_286 );

    SC_METHOD(thread_grp_fu_297_p0);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_1_reg_215 );
    sensitive << ( tmp_9_reg_250 );
    sensitive << ( ap_phi_mux_h3_phi_fu_278_p4 );
    sensitive << ( h3_reg_274 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( ap_CS_fsm_state48 );

    SC_METHOD(thread_grp_fu_297_p1);
    sensitive << ( reg_338 );
    sensitive << ( theta1b2_load_reg_692 );
    sensitive << ( theta2b4_load_reg_758 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state29 );
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( ap_CS_fsm_state48 );

    SC_METHOD(thread_grp_fu_306_p0);
    sensitive << ( X_Dout_A );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( h1_q0 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( h2_load_reg_786 );
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_grp_fu_306_p1);
    sensitive << ( theta1h1_load_reg_682 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( theta2h3_load_reg_748 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( theta3h5_load_reg_791 );
    sensitive << ( ap_CS_fsm_state44 );

    SC_METHOD(thread_h1_address0);
    sensitive << ( h1_addr_reg_654 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_17_fu_548_p1 );

    SC_METHOD(thread_h1_ce0);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_h1_d0);
    sensitive << ( reg_349 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_22_fu_461_p2 );

    SC_METHOD(thread_h1_we0);
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_h2_address0);
    sensitive << ( h2_addr_reg_720 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( tmp_13_fu_615_p1 );

    SC_METHOD(thread_h2_ce0);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( ap_CS_fsm_state41 );

    SC_METHOD(thread_h2_d0);
    sensitive << ( reg_349 );
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( tmp_27_fu_589_p2 );

    SC_METHOD(thread_h2_we0);
    sensitive << ( ap_CS_fsm_state41 );

    SC_METHOD(thread_i_3_fu_361_p2);
    sensitive << ( i_reg_204 );

    SC_METHOD(thread_i_4_fu_609_p2);
    sensitive << ( i_2_reg_286 );

    SC_METHOD(thread_i_5_fu_481_p2);
    sensitive << ( i_1_reg_239 );

    SC_METHOD(thread_j_2_fu_382_p2);
    sensitive << ( j_reg_227 );

    SC_METHOD(thread_j_3_fu_502_p2);
    sensitive << ( j_1_reg_262 );

    SC_METHOD(thread_notlhs7_fu_571_p2);
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( tmp_23_fu_557_p4 );

    SC_METHOD(thread_notlhs_fu_443_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_4_fu_429_p4 );

    SC_METHOD(thread_notrhs8_fu_577_p2);
    sensitive << ( ap_CS_fsm_state41 );
    sensitive << ( tmp_30_fu_567_p1 );

    SC_METHOD(thread_notrhs_fu_449_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_16_fu_439_p1 );

    SC_METHOD(thread_p_shl1_cast_fu_516_p1);
    sensitive << ( tmp_31_fu_508_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_528_p1);
    sensitive << ( tmp_32_fu_520_p3 );

    SC_METHOD(thread_p_shl_cast_fu_400_p1);
    sensitive << ( tmp_24_fu_392_p3 );

    SC_METHOD(thread_theta1b2_address0);
    sensitive << ( tmp_reg_644 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_theta1b2_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_theta1h1_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_30_cast_fu_415_p1 );

    SC_METHOD(thread_theta1h1_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_theta2b4_address0);
    sensitive << ( tmp_2_reg_710 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_theta2b4_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_theta2h3_address0);
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( tmp_34_cast_fu_543_p1 );

    SC_METHOD(thread_theta2h3_ce0);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_theta3h5_address0);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_13_fu_615_p1 );

    SC_METHOD(thread_theta3h5_ce0);
    sensitive << ( ap_CS_fsm_state42 );

    SC_METHOD(thread_tmp_13_fu_615_p1);
    sensitive << ( i_2_reg_286 );

    SC_METHOD(thread_tmp_15_to_int_fu_553_p1);
    sensitive << ( reg_349 );

    SC_METHOD(thread_tmp_16_fu_439_p1);
    sensitive << ( tmp_3_to_int_fu_425_p1 );

    SC_METHOD(thread_tmp_17_fu_548_p1);
    sensitive << ( j_1_reg_262 );

    SC_METHOD(thread_tmp_20_fu_455_p2);
    sensitive << ( notrhs_fu_449_p2 );
    sensitive << ( notlhs_fu_443_p2 );

    SC_METHOD(thread_tmp_22_fu_461_p2);
    sensitive << ( tmp_21_reg_697 );
    sensitive << ( tmp_20_fu_455_p2 );

    SC_METHOD(thread_tmp_23_fu_557_p4);
    sensitive << ( tmp_15_to_int_fu_553_p1 );

    SC_METHOD(thread_tmp_24_fu_392_p3);
    sensitive << ( j_reg_227 );

    SC_METHOD(thread_tmp_25_fu_583_p2);
    sensitive << ( notrhs8_fu_577_p2 );
    sensitive << ( notlhs7_fu_571_p2 );

    SC_METHOD(thread_tmp_27_fu_589_p2);
    sensitive << ( tmp_26_reg_763 );
    sensitive << ( tmp_25_fu_583_p2 );

    SC_METHOD(thread_tmp_28_fu_404_p2);
    sensitive << ( p_shl_cast_fu_400_p1 );
    sensitive << ( tmp_5_cast_fu_388_p1 );

    SC_METHOD(thread_tmp_29_fu_410_p2);
    sensitive << ( tmp_cast_reg_649 );
    sensitive << ( tmp_28_fu_404_p2 );

    SC_METHOD(thread_tmp_2_cast_fu_492_p1);
    sensitive << ( i_1_reg_239 );

    SC_METHOD(thread_tmp_2_fu_487_p1);
    sensitive << ( i_1_reg_239 );

    SC_METHOD(thread_tmp_30_cast_fu_415_p1);
    sensitive << ( tmp_29_fu_410_p2 );

    SC_METHOD(thread_tmp_30_fu_567_p1);
    sensitive << ( tmp_15_to_int_fu_553_p1 );

    SC_METHOD(thread_tmp_31_fu_508_p3);
    sensitive << ( j_1_reg_262 );

    SC_METHOD(thread_tmp_32_fu_520_p3);
    sensitive << ( j_1_reg_262 );

    SC_METHOD(thread_tmp_33_fu_532_p2);
    sensitive << ( p_shl1_cast_fu_516_p1 );
    sensitive << ( p_shl2_cast_fu_528_p1 );

    SC_METHOD(thread_tmp_34_cast_fu_543_p1);
    sensitive << ( tmp_34_fu_538_p2 );

    SC_METHOD(thread_tmp_34_fu_538_p2);
    sensitive << ( tmp_2_cast_reg_715 );
    sensitive << ( tmp_33_fu_532_p2 );

    SC_METHOD(thread_tmp_3_to_int_fu_425_p1);
    sensitive << ( reg_349 );

    SC_METHOD(thread_tmp_4_fu_429_p4);
    sensitive << ( tmp_3_to_int_fu_425_p1 );

    SC_METHOD(thread_tmp_5_cast_fu_388_p1);
    sensitive << ( j_reg_227 );

    SC_METHOD(thread_tmp_5_fu_420_p1);
    sensitive << ( j_reg_227 );

    SC_METHOD(thread_tmp_8_fu_315_p0);
    sensitive << ( ap_CS_fsm_state57 );
    sensitive << ( tmp_neg_fu_625_p2 );

    SC_METHOD(thread_tmp_cast_fu_372_p1);
    sensitive << ( i_reg_204 );

    SC_METHOD(thread_tmp_fu_367_p1);
    sensitive << ( i_reg_204 );

    SC_METHOD(thread_tmp_neg_fu_625_p2);
    sensitive << ( tmp_to_int_fu_621_p1 );

    SC_METHOD(thread_tmp_to_int_fu_621_p1);
    sensitive << ( reg_343 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond4_fu_355_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond3_fu_376_p2 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( exitcond2_fu_475_p2 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( exitcond1_fu_496_p2 );
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( exitcond_fu_603_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const4);

    ap_CS_fsm = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hand_num_nn_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, X_Addr_A, "(port)X_Addr_A");
    sc_trace(mVcdFile, X_EN_A, "(port)X_EN_A");
    sc_trace(mVcdFile, X_WEN_A, "(port)X_WEN_A");
    sc_trace(mVcdFile, X_Din_A, "(port)X_Din_A");
    sc_trace(mVcdFile, X_Dout_A, "(port)X_Dout_A");
    sc_trace(mVcdFile, X_Clk_A, "(port)X_Clk_A");
    sc_trace(mVcdFile, X_Rst_A, "(port)X_Rst_A");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWVALID, "(port)s_axi_CRTL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWREADY, "(port)s_axi_CRTL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWADDR, "(port)s_axi_CRTL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WVALID, "(port)s_axi_CRTL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WREADY, "(port)s_axi_CRTL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WDATA, "(port)s_axi_CRTL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WSTRB, "(port)s_axi_CRTL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARVALID, "(port)s_axi_CRTL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARREADY, "(port)s_axi_CRTL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARADDR, "(port)s_axi_CRTL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RVALID, "(port)s_axi_CRTL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RREADY, "(port)s_axi_CRTL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RDATA, "(port)s_axi_CRTL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RRESP, "(port)s_axi_CRTL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BVALID, "(port)s_axi_CRTL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BREADY, "(port)s_axi_CRTL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BRESP, "(port)s_axi_CRTL_BUS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, y, "y");
    sc_trace(mVcdFile, theta1h1_address0, "theta1h1_address0");
    sc_trace(mVcdFile, theta1h1_ce0, "theta1h1_ce0");
    sc_trace(mVcdFile, theta1h1_q0, "theta1h1_q0");
    sc_trace(mVcdFile, theta1b2_address0, "theta1b2_address0");
    sc_trace(mVcdFile, theta1b2_ce0, "theta1b2_ce0");
    sc_trace(mVcdFile, theta1b2_q0, "theta1b2_q0");
    sc_trace(mVcdFile, theta2h3_address0, "theta2h3_address0");
    sc_trace(mVcdFile, theta2h3_ce0, "theta2h3_ce0");
    sc_trace(mVcdFile, theta2h3_q0, "theta2h3_q0");
    sc_trace(mVcdFile, theta2b4_address0, "theta2b4_address0");
    sc_trace(mVcdFile, theta2b4_ce0, "theta2b4_ce0");
    sc_trace(mVcdFile, theta2b4_q0, "theta2b4_q0");
    sc_trace(mVcdFile, theta3h5_address0, "theta3h5_address0");
    sc_trace(mVcdFile, theta3h5_ce0, "theta3h5_ce0");
    sc_trace(mVcdFile, theta3h5_q0, "theta3h5_q0");
    sc_trace(mVcdFile, grp_fu_306_p2, "grp_fu_306_p2");
    sc_trace(mVcdFile, reg_338, "reg_338");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, ap_CS_fsm_state47, "ap_CS_fsm_state47");
    sc_trace(mVcdFile, grp_fu_297_p2, "grp_fu_297_p2");
    sc_trace(mVcdFile, reg_343, "reg_343");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, ap_CS_fsm_state56, "ap_CS_fsm_state56");
    sc_trace(mVcdFile, reg_349, "reg_349");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state39, "ap_CS_fsm_state39");
    sc_trace(mVcdFile, ap_CS_fsm_state52, "ap_CS_fsm_state52");
    sc_trace(mVcdFile, i_3_fu_361_p2, "i_3_fu_361_p2");
    sc_trace(mVcdFile, i_3_reg_639, "i_3_reg_639");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_367_p1, "tmp_fu_367_p1");
    sc_trace(mVcdFile, tmp_reg_644, "tmp_reg_644");
    sc_trace(mVcdFile, exitcond4_fu_355_p2, "exitcond4_fu_355_p2");
    sc_trace(mVcdFile, tmp_cast_fu_372_p1, "tmp_cast_fu_372_p1");
    sc_trace(mVcdFile, tmp_cast_reg_649, "tmp_cast_reg_649");
    sc_trace(mVcdFile, h1_addr_reg_654, "h1_addr_reg_654");
    sc_trace(mVcdFile, j_2_fu_382_p2, "j_2_fu_382_p2");
    sc_trace(mVcdFile, j_2_reg_662, "j_2_reg_662");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, exitcond3_fu_376_p2, "exitcond3_fu_376_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, theta1h1_load_reg_682, "theta1h1_load_reg_682");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, theta1b2_load_reg_692, "theta1b2_load_reg_692");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_fu_318_p2, "grp_fu_318_p2");
    sc_trace(mVcdFile, tmp_21_reg_697, "tmp_21_reg_697");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, i_5_fu_481_p2, "i_5_fu_481_p2");
    sc_trace(mVcdFile, i_5_reg_705, "i_5_reg_705");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, tmp_2_fu_487_p1, "tmp_2_fu_487_p1");
    sc_trace(mVcdFile, tmp_2_reg_710, "tmp_2_reg_710");
    sc_trace(mVcdFile, exitcond2_fu_475_p2, "exitcond2_fu_475_p2");
    sc_trace(mVcdFile, tmp_2_cast_fu_492_p1, "tmp_2_cast_fu_492_p1");
    sc_trace(mVcdFile, tmp_2_cast_reg_715, "tmp_2_cast_reg_715");
    sc_trace(mVcdFile, h2_addr_reg_720, "h2_addr_reg_720");
    sc_trace(mVcdFile, j_3_fu_502_p2, "j_3_fu_502_p2");
    sc_trace(mVcdFile, j_3_reg_728, "j_3_reg_728");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, exitcond1_fu_496_p2, "exitcond1_fu_496_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, theta2h3_load_reg_748, "theta2h3_load_reg_748");
    sc_trace(mVcdFile, h1_q0, "h1_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, theta2b4_load_reg_758, "theta2b4_load_reg_758");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, tmp_26_reg_763, "tmp_26_reg_763");
    sc_trace(mVcdFile, ap_CS_fsm_state40, "ap_CS_fsm_state40");
    sc_trace(mVcdFile, i_4_fu_609_p2, "i_4_fu_609_p2");
    sc_trace(mVcdFile, i_4_reg_771, "i_4_reg_771");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, exitcond_fu_603_p2, "exitcond_fu_603_p2");
    sc_trace(mVcdFile, h2_q0, "h2_q0");
    sc_trace(mVcdFile, h2_load_reg_786, "h2_load_reg_786");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, theta3h5_load_reg_791, "theta3h5_load_reg_791");
    sc_trace(mVcdFile, tmp_8_fu_315_p1, "tmp_8_fu_315_p1");
    sc_trace(mVcdFile, tmp_8_reg_796, "tmp_8_reg_796");
    sc_trace(mVcdFile, ap_CS_fsm_state57, "ap_CS_fsm_state57");
    sc_trace(mVcdFile, grp_fu_333_p2, "grp_fu_333_p2");
    sc_trace(mVcdFile, tmp_10_reg_801, "tmp_10_reg_801");
    sc_trace(mVcdFile, ap_CS_fsm_state75, "ap_CS_fsm_state75");
    sc_trace(mVcdFile, grp_fu_323_p2, "grp_fu_323_p2");
    sc_trace(mVcdFile, tmp_11_reg_806, "tmp_11_reg_806");
    sc_trace(mVcdFile, ap_CS_fsm_state81, "ap_CS_fsm_state81");
    sc_trace(mVcdFile, grp_fu_328_p2, "grp_fu_328_p2");
    sc_trace(mVcdFile, tmp_12_reg_811, "tmp_12_reg_811");
    sc_trace(mVcdFile, ap_CS_fsm_state112, "ap_CS_fsm_state112");
    sc_trace(mVcdFile, h1_address0, "h1_address0");
    sc_trace(mVcdFile, h1_ce0, "h1_ce0");
    sc_trace(mVcdFile, h1_we0, "h1_we0");
    sc_trace(mVcdFile, h1_d0, "h1_d0");
    sc_trace(mVcdFile, h2_address0, "h2_address0");
    sc_trace(mVcdFile, h2_ce0, "h2_ce0");
    sc_trace(mVcdFile, h2_we0, "h2_we0");
    sc_trace(mVcdFile, h2_d0, "h2_d0");
    sc_trace(mVcdFile, i_reg_204, "i_reg_204");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, tmp_1_reg_215, "tmp_1_reg_215");
    sc_trace(mVcdFile, j_reg_227, "j_reg_227");
    sc_trace(mVcdFile, i_1_reg_239, "i_1_reg_239");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, tmp_9_reg_250, "tmp_9_reg_250");
    sc_trace(mVcdFile, j_1_reg_262, "j_1_reg_262");
    sc_trace(mVcdFile, ap_phi_mux_h3_phi_fu_278_p4, "ap_phi_mux_h3_phi_fu_278_p4");
    sc_trace(mVcdFile, h3_reg_274, "h3_reg_274");
    sc_trace(mVcdFile, i_2_reg_286, "i_2_reg_286");
    sc_trace(mVcdFile, tmp_30_cast_fu_415_p1, "tmp_30_cast_fu_415_p1");
    sc_trace(mVcdFile, tmp_5_fu_420_p1, "tmp_5_fu_420_p1");
    sc_trace(mVcdFile, tmp_34_cast_fu_543_p1, "tmp_34_cast_fu_543_p1");
    sc_trace(mVcdFile, tmp_17_fu_548_p1, "tmp_17_fu_548_p1");
    sc_trace(mVcdFile, tmp_13_fu_615_p1, "tmp_13_fu_615_p1");
    sc_trace(mVcdFile, X_Addr_A_orig, "X_Addr_A_orig");
    sc_trace(mVcdFile, grp_fu_297_p0, "grp_fu_297_p0");
    sc_trace(mVcdFile, grp_fu_297_p1, "grp_fu_297_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, ap_CS_fsm_state48, "ap_CS_fsm_state48");
    sc_trace(mVcdFile, grp_fu_306_p0, "grp_fu_306_p0");
    sc_trace(mVcdFile, grp_fu_306_p1, "grp_fu_306_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state44, "ap_CS_fsm_state44");
    sc_trace(mVcdFile, ap_CS_fsm_state113, "ap_CS_fsm_state113");
    sc_trace(mVcdFile, tmp_8_fu_315_p0, "tmp_8_fu_315_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state76, "ap_CS_fsm_state76");
    sc_trace(mVcdFile, ap_CS_fsm_state82, "ap_CS_fsm_state82");
    sc_trace(mVcdFile, ap_CS_fsm_state58, "ap_CS_fsm_state58");
    sc_trace(mVcdFile, tmp_24_fu_392_p3, "tmp_24_fu_392_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_400_p1, "p_shl_cast_fu_400_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_388_p1, "tmp_5_cast_fu_388_p1");
    sc_trace(mVcdFile, tmp_28_fu_404_p2, "tmp_28_fu_404_p2");
    sc_trace(mVcdFile, tmp_29_fu_410_p2, "tmp_29_fu_410_p2");
    sc_trace(mVcdFile, tmp_3_to_int_fu_425_p1, "tmp_3_to_int_fu_425_p1");
    sc_trace(mVcdFile, tmp_4_fu_429_p4, "tmp_4_fu_429_p4");
    sc_trace(mVcdFile, tmp_16_fu_439_p1, "tmp_16_fu_439_p1");
    sc_trace(mVcdFile, notrhs_fu_449_p2, "notrhs_fu_449_p2");
    sc_trace(mVcdFile, notlhs_fu_443_p2, "notlhs_fu_443_p2");
    sc_trace(mVcdFile, tmp_20_fu_455_p2, "tmp_20_fu_455_p2");
    sc_trace(mVcdFile, tmp_22_fu_461_p2, "tmp_22_fu_461_p2");
    sc_trace(mVcdFile, tmp_31_fu_508_p3, "tmp_31_fu_508_p3");
    sc_trace(mVcdFile, tmp_32_fu_520_p3, "tmp_32_fu_520_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_516_p1, "p_shl1_cast_fu_516_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_528_p1, "p_shl2_cast_fu_528_p1");
    sc_trace(mVcdFile, tmp_33_fu_532_p2, "tmp_33_fu_532_p2");
    sc_trace(mVcdFile, tmp_34_fu_538_p2, "tmp_34_fu_538_p2");
    sc_trace(mVcdFile, tmp_15_to_int_fu_553_p1, "tmp_15_to_int_fu_553_p1");
    sc_trace(mVcdFile, tmp_23_fu_557_p4, "tmp_23_fu_557_p4");
    sc_trace(mVcdFile, tmp_30_fu_567_p1, "tmp_30_fu_567_p1");
    sc_trace(mVcdFile, notrhs8_fu_577_p2, "notrhs8_fu_577_p2");
    sc_trace(mVcdFile, notlhs7_fu_571_p2, "notlhs7_fu_571_p2");
    sc_trace(mVcdFile, tmp_25_fu_583_p2, "tmp_25_fu_583_p2");
    sc_trace(mVcdFile, tmp_27_fu_589_p2, "tmp_27_fu_589_p2");
    sc_trace(mVcdFile, tmp_to_int_fu_621_p1, "tmp_to_int_fu_621_p1");
    sc_trace(mVcdFile, tmp_neg_fu_625_p2, "tmp_neg_fu_625_p2");
    sc_trace(mVcdFile, h3_2_fu_312_p1, "h3_2_fu_312_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_return, "ap_return");
#endif

    }
    mHdltvinHandle.open("hand_num_nn.hdltvin.dat");
    mHdltvoutHandle.open("hand_num_nn.hdltvout.dat");
}

hand_num_nn::~hand_num_nn() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete theta1h1_U;
    delete theta1b2_U;
    delete theta2h3_U;
    delete theta2b4_U;
    delete theta3h5_U;
    delete hand_num_nn_CRTL_BUS_s_axi_U;
    delete h1_U;
    delete h2_U;
    delete hand_num_nn_fadd_g8j_U1;
    delete hand_num_nn_fmul_hbi_U2;
    delete hand_num_nn_fptruibs_U3;
    delete hand_num_nn_fpextjbC_U4;
    delete hand_num_nn_fcmp_kbM_U5;
    delete hand_num_nn_dadd_lbW_U6;
    delete hand_num_nn_ddiv_mb6_U7;
    delete hand_num_nn_dexp_ncg_U8;
}

void hand_num_nn::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void hand_num_nn::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_0;
}

void hand_num_nn::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv64_3FF0000000000000;
}

void hand_num_nn::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_4;
}

void hand_num_nn::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv64_0;
}

void hand_num_nn::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_475_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        h3_reg_274 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state52.read())) {
        h3_reg_274 = grp_fu_297_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond4_fu_355_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i_1_reg_239 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        i_1_reg_239 = i_5_reg_705.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_475_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        i_2_reg_286 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state52.read())) {
        i_2_reg_286 = i_4_reg_771.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        i_reg_204 = i_3_reg_639.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_204 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        j_1_reg_262 = j_3_reg_728.read();
    } else if ((esl_seteq<1,1,1>(exitcond2_fu_475_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        j_1_reg_262 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_reg_227 = j_2_reg_662.read();
    } else if ((esl_seteq<1,1,1>(exitcond4_fu_355_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_reg_227 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmp_1_reg_215 = grp_fu_297_p2.read();
    } else if ((esl_seteq<1,1,1>(exitcond4_fu_355_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        tmp_1_reg_215 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        tmp_9_reg_250 = grp_fu_297_p2.read();
    } else if ((esl_seteq<1,1,1>(exitcond2_fu_475_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        tmp_9_reg_250 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(exitcond4_fu_355_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        h1_addr_reg_654 =  (sc_lv<4>) (tmp_fu_367_p1.read());
        tmp_cast_reg_649 = tmp_cast_fu_372_p1.read();
        tmp_reg_644 = tmp_fu_367_p1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_475_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        h2_addr_reg_720 =  (sc_lv<5>) (tmp_2_fu_487_p1.read());
        tmp_2_cast_reg_715 = tmp_2_cast_fu_492_p1.read();
        tmp_2_reg_710 = tmp_2_fu_487_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        h2_load_reg_786 = h2_q0.read();
        theta3h5_load_reg_791 = theta3h5_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_3_reg_639 = i_3_fu_361_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        i_4_reg_771 = i_4_fu_609_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        i_5_reg_705 = i_5_fu_481_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_2_reg_662 = j_2_fu_382_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        j_3_reg_728 = j_3_fu_502_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state47.read()))) {
        reg_338 = grp_fu_306_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state56.read()))) {
        reg_343 = grp_fu_297_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state52.read()))) {
        reg_349 = grp_fu_297_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        theta1b2_load_reg_692 = theta1b2_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        theta1h1_load_reg_682 = theta1h1_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read())) {
        theta2b4_load_reg_758 = theta2b4_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        theta2h3_load_reg_748 = theta2h3_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state75.read())) {
        tmp_10_reg_801 = grp_fu_333_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state81.read())) {
        tmp_11_reg_806 = grp_fu_323_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state112.read())) {
        tmp_12_reg_811 = grp_fu_328_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        tmp_21_reg_697 = grp_fu_318_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        tmp_26_reg_763 = grp_fu_318_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state57.read())) {
        tmp_8_reg_796 = tmp_8_fu_315_p1.read();
    }
}

void hand_num_nn::thread_X_Addr_A() {
    X_Addr_A = (!ap_const_lv32_2.is_01())? sc_lv<32>(): X_Addr_A_orig.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void hand_num_nn::thread_X_Addr_A_orig() {
    X_Addr_A_orig =  (sc_lv<32>) (tmp_5_fu_420_p1.read());
}

void hand_num_nn::thread_X_Clk_A() {
    X_Clk_A = ap_clk.read()? SC_LOGIC_1 : SC_LOGIC_0;
}

void hand_num_nn::thread_X_Din_A() {
    X_Din_A = ap_const_lv32_0;
}

void hand_num_nn::thread_X_EN_A() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        X_EN_A = ap_const_logic_1;
    } else {
        X_EN_A = ap_const_logic_0;
    }
}

void hand_num_nn::thread_X_Rst_A() {
    X_Rst_A =  (sc_logic) (~ap_rst_n.read());
}

void hand_num_nn::thread_X_WEN_A() {
    X_WEN_A = ap_const_lv4_0;
}

void hand_num_nn::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void hand_num_nn::thread_ap_CS_fsm_state112() {
    ap_CS_fsm_state112 = ap_CS_fsm.read()[111];
}

void hand_num_nn::thread_ap_CS_fsm_state113() {
    ap_CS_fsm_state113 = ap_CS_fsm.read()[112];
}

void hand_num_nn::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void hand_num_nn::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void hand_num_nn::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void hand_num_nn::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void hand_num_nn::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void hand_num_nn::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void hand_num_nn::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void hand_num_nn::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void hand_num_nn::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void hand_num_nn::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void hand_num_nn::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void hand_num_nn::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void hand_num_nn::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void hand_num_nn::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void hand_num_nn::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read()[32];
}

void hand_num_nn::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void hand_num_nn::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read()[34];
}

void hand_num_nn::thread_ap_CS_fsm_state39() {
    ap_CS_fsm_state39 = ap_CS_fsm.read()[38];
}

void hand_num_nn::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void hand_num_nn::thread_ap_CS_fsm_state40() {
    ap_CS_fsm_state40 = ap_CS_fsm.read()[39];
}

void hand_num_nn::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void hand_num_nn::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void hand_num_nn::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void hand_num_nn::thread_ap_CS_fsm_state44() {
    ap_CS_fsm_state44 = ap_CS_fsm.read()[43];
}

void hand_num_nn::thread_ap_CS_fsm_state47() {
    ap_CS_fsm_state47 = ap_CS_fsm.read()[46];
}

void hand_num_nn::thread_ap_CS_fsm_state48() {
    ap_CS_fsm_state48 = ap_CS_fsm.read()[47];
}

void hand_num_nn::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void hand_num_nn::thread_ap_CS_fsm_state52() {
    ap_CS_fsm_state52 = ap_CS_fsm.read()[51];
}

void hand_num_nn::thread_ap_CS_fsm_state56() {
    ap_CS_fsm_state56 = ap_CS_fsm.read()[55];
}

void hand_num_nn::thread_ap_CS_fsm_state57() {
    ap_CS_fsm_state57 = ap_CS_fsm.read()[56];
}

void hand_num_nn::thread_ap_CS_fsm_state58() {
    ap_CS_fsm_state58 = ap_CS_fsm.read()[57];
}

void hand_num_nn::thread_ap_CS_fsm_state75() {
    ap_CS_fsm_state75 = ap_CS_fsm.read()[74];
}

void hand_num_nn::thread_ap_CS_fsm_state76() {
    ap_CS_fsm_state76 = ap_CS_fsm.read()[75];
}

void hand_num_nn::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void hand_num_nn::thread_ap_CS_fsm_state81() {
    ap_CS_fsm_state81 = ap_CS_fsm.read()[80];
}

void hand_num_nn::thread_ap_CS_fsm_state82() {
    ap_CS_fsm_state82 = ap_CS_fsm.read()[81];
}

void hand_num_nn::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void hand_num_nn::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state113.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void hand_num_nn::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void hand_num_nn::thread_ap_phi_mux_h3_phi_fu_278_p4() {
    ap_phi_mux_h3_phi_fu_278_p4 = h3_reg_274.read();
}

void hand_num_nn::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state113.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void hand_num_nn::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void hand_num_nn::thread_exitcond1_fu_496_p2() {
    exitcond1_fu_496_p2 = (!j_1_reg_262.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<1>(): sc_lv<1>(j_1_reg_262.read() == ap_const_lv4_F);
}

void hand_num_nn::thread_exitcond2_fu_475_p2() {
    exitcond2_fu_475_p2 = (!i_1_reg_239.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_239.read() == ap_const_lv5_1E);
}

void hand_num_nn::thread_exitcond3_fu_376_p2() {
    exitcond3_fu_376_p2 = (!j_reg_227.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_227.read() == ap_const_lv3_7);
}

void hand_num_nn::thread_exitcond4_fu_355_p2() {
    exitcond4_fu_355_p2 = (!i_reg_204.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_204.read() == ap_const_lv4_F);
}

void hand_num_nn::thread_exitcond_fu_603_p2() {
    exitcond_fu_603_p2 = (!i_2_reg_286.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_286.read() == ap_const_lv5_1E);
}

void hand_num_nn::thread_grp_fu_297_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state48.read())) {
        grp_fu_297_p0 = h3_reg_274.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        grp_fu_297_p0 = ap_phi_mux_h3_phi_fu_278_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read()))) {
        grp_fu_297_p0 = tmp_9_reg_250.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        grp_fu_297_p0 = tmp_1_reg_215.read();
    } else {
        grp_fu_297_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void hand_num_nn::thread_grp_fu_297_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        grp_fu_297_p1 = ap_const_lv32_BEC56142;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        grp_fu_297_p1 = theta2b4_load_reg_758.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_297_p1 = theta1b2_load_reg_692.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state48.read()))) {
        grp_fu_297_p1 = reg_338.read();
    } else {
        grp_fu_297_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void hand_num_nn::thread_grp_fu_306_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        grp_fu_306_p0 = h2_load_reg_786.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        grp_fu_306_p0 = h1_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_306_p0 = X_Dout_A.read();
    } else {
        grp_fu_306_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void hand_num_nn::thread_grp_fu_306_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state44.read())) {
        grp_fu_306_p1 = theta3h5_load_reg_791.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        grp_fu_306_p1 = theta2h3_load_reg_748.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_306_p1 = theta1h1_load_reg_682.read();
    } else {
        grp_fu_306_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void hand_num_nn::thread_h1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        h1_address0 =  (sc_lv<4>) (tmp_17_fu_548_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        h1_address0 = h1_addr_reg_654.read();
    } else {
        h1_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void hand_num_nn::thread_h1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        h1_ce0 = ap_const_logic_1;
    } else {
        h1_ce0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_h1_d0() {
    h1_d0 = (!tmp_22_fu_461_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_22_fu_461_p2.read()[0].to_bool())? ap_const_lv32_0: reg_349.read());
}

void hand_num_nn::thread_h1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        h1_we0 = ap_const_logic_1;
    } else {
        h1_we0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_h2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        h2_address0 =  (sc_lv<5>) (tmp_13_fu_615_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        h2_address0 = h2_addr_reg_720.read();
    } else {
        h2_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void hand_num_nn::thread_h2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read()))) {
        h2_ce0 = ap_const_logic_1;
    } else {
        h2_ce0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_h2_d0() {
    h2_d0 = (!tmp_27_fu_589_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_27_fu_589_p2.read()[0].to_bool())? ap_const_lv32_0: reg_349.read());
}

void hand_num_nn::thread_h2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        h2_we0 = ap_const_logic_1;
    } else {
        h2_we0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_i_3_fu_361_p2() {
    i_3_fu_361_p2 = (!i_reg_204.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_204.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void hand_num_nn::thread_i_4_fu_609_p2() {
    i_4_fu_609_p2 = (!i_2_reg_286.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_2_reg_286.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void hand_num_nn::thread_i_5_fu_481_p2() {
    i_5_fu_481_p2 = (!i_1_reg_239.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_1_reg_239.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void hand_num_nn::thread_j_2_fu_382_p2() {
    j_2_fu_382_p2 = (!j_reg_227.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_reg_227.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void hand_num_nn::thread_j_3_fu_502_p2() {
    j_3_fu_502_p2 = (!j_1_reg_262.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_1_reg_262.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void hand_num_nn::thread_notlhs7_fu_571_p2() {
    notlhs7_fu_571_p2 = (!tmp_23_fu_557_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_fu_557_p4.read() != ap_const_lv8_FF);
}

void hand_num_nn::thread_notlhs_fu_443_p2() {
    notlhs_fu_443_p2 = (!tmp_4_fu_429_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_429_p4.read() != ap_const_lv8_FF);
}

void hand_num_nn::thread_notrhs8_fu_577_p2() {
    notrhs8_fu_577_p2 = (!tmp_30_fu_567_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_fu_567_p1.read() == ap_const_lv23_0);
}

void hand_num_nn::thread_notrhs_fu_449_p2() {
    notrhs_fu_449_p2 = (!tmp_16_fu_439_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_16_fu_439_p1.read() == ap_const_lv23_0);
}

void hand_num_nn::thread_p_shl1_cast_fu_516_p1() {
    p_shl1_cast_fu_516_p1 = esl_zext<10,9>(tmp_31_fu_508_p3.read());
}

void hand_num_nn::thread_p_shl2_cast_fu_528_p1() {
    p_shl2_cast_fu_528_p1 = esl_zext<10,5>(tmp_32_fu_520_p3.read());
}

void hand_num_nn::thread_p_shl_cast_fu_400_p1() {
    p_shl_cast_fu_400_p1 = esl_zext<8,7>(tmp_24_fu_392_p3.read());
}

void hand_num_nn::thread_theta1b2_address0() {
    theta1b2_address0 =  (sc_lv<4>) (tmp_reg_644.read());
}

void hand_num_nn::thread_theta1b2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        theta1b2_ce0 = ap_const_logic_1;
    } else {
        theta1b2_ce0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_theta1h1_address0() {
    theta1h1_address0 =  (sc_lv<7>) (tmp_30_cast_fu_415_p1.read());
}

void hand_num_nn::thread_theta1h1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        theta1h1_ce0 = ap_const_logic_1;
    } else {
        theta1h1_ce0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_theta2b4_address0() {
    theta2b4_address0 =  (sc_lv<5>) (tmp_2_reg_710.read());
}

void hand_num_nn::thread_theta2b4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        theta2b4_ce0 = ap_const_logic_1;
    } else {
        theta2b4_ce0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_theta2h3_address0() {
    theta2h3_address0 =  (sc_lv<9>) (tmp_34_cast_fu_543_p1.read());
}

void hand_num_nn::thread_theta2h3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        theta2h3_ce0 = ap_const_logic_1;
    } else {
        theta2h3_ce0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_theta3h5_address0() {
    theta3h5_address0 =  (sc_lv<5>) (tmp_13_fu_615_p1.read());
}

void hand_num_nn::thread_theta3h5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        theta3h5_ce0 = ap_const_logic_1;
    } else {
        theta3h5_ce0 = ap_const_logic_0;
    }
}

void hand_num_nn::thread_tmp_13_fu_615_p1() {
    tmp_13_fu_615_p1 = esl_zext<64,5>(i_2_reg_286.read());
}

void hand_num_nn::thread_tmp_15_to_int_fu_553_p1() {
    tmp_15_to_int_fu_553_p1 = reg_349.read();
}

void hand_num_nn::thread_tmp_16_fu_439_p1() {
    tmp_16_fu_439_p1 = tmp_3_to_int_fu_425_p1.read().range(23-1, 0);
}

void hand_num_nn::thread_tmp_17_fu_548_p1() {
    tmp_17_fu_548_p1 = esl_zext<64,4>(j_1_reg_262.read());
}

void hand_num_nn::thread_tmp_20_fu_455_p2() {
    tmp_20_fu_455_p2 = (notrhs_fu_449_p2.read() | notlhs_fu_443_p2.read());
}

void hand_num_nn::thread_tmp_22_fu_461_p2() {
    tmp_22_fu_461_p2 = (tmp_20_fu_455_p2.read() & tmp_21_reg_697.read());
}

void hand_num_nn::thread_tmp_23_fu_557_p4() {
    tmp_23_fu_557_p4 = tmp_15_to_int_fu_553_p1.read().range(30, 23);
}

void hand_num_nn::thread_tmp_24_fu_392_p3() {
    tmp_24_fu_392_p3 = esl_concat<3,4>(j_reg_227.read(), ap_const_lv4_0);
}

void hand_num_nn::thread_tmp_25_fu_583_p2() {
    tmp_25_fu_583_p2 = (notrhs8_fu_577_p2.read() | notlhs7_fu_571_p2.read());
}

void hand_num_nn::thread_tmp_27_fu_589_p2() {
    tmp_27_fu_589_p2 = (tmp_25_fu_583_p2.read() & tmp_26_reg_763.read());
}

void hand_num_nn::thread_tmp_28_fu_404_p2() {
    tmp_28_fu_404_p2 = (!p_shl_cast_fu_400_p1.read().is_01() || !tmp_5_cast_fu_388_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl_cast_fu_400_p1.read()) - sc_biguint<8>(tmp_5_cast_fu_388_p1.read()));
}

void hand_num_nn::thread_tmp_29_fu_410_p2() {
    tmp_29_fu_410_p2 = (!tmp_28_fu_404_p2.read().is_01() || !tmp_cast_reg_649.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_28_fu_404_p2.read()) + sc_biguint<8>(tmp_cast_reg_649.read()));
}

void hand_num_nn::thread_tmp_2_cast_fu_492_p1() {
    tmp_2_cast_fu_492_p1 = esl_zext<10,5>(i_1_reg_239.read());
}

void hand_num_nn::thread_tmp_2_fu_487_p1() {
    tmp_2_fu_487_p1 = esl_zext<64,5>(i_1_reg_239.read());
}

void hand_num_nn::thread_tmp_30_cast_fu_415_p1() {
    tmp_30_cast_fu_415_p1 = esl_sext<64,8>(tmp_29_fu_410_p2.read());
}

void hand_num_nn::thread_tmp_30_fu_567_p1() {
    tmp_30_fu_567_p1 = tmp_15_to_int_fu_553_p1.read().range(23-1, 0);
}

void hand_num_nn::thread_tmp_31_fu_508_p3() {
    tmp_31_fu_508_p3 = esl_concat<4,5>(j_1_reg_262.read(), ap_const_lv5_0);
}

void hand_num_nn::thread_tmp_32_fu_520_p3() {
    tmp_32_fu_520_p3 = esl_concat<4,1>(j_1_reg_262.read(), ap_const_lv1_0);
}

void hand_num_nn::thread_tmp_33_fu_532_p2() {
    tmp_33_fu_532_p2 = (!p_shl1_cast_fu_516_p1.read().is_01() || !p_shl2_cast_fu_528_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(p_shl1_cast_fu_516_p1.read()) - sc_biguint<10>(p_shl2_cast_fu_528_p1.read()));
}

void hand_num_nn::thread_tmp_34_cast_fu_543_p1() {
    tmp_34_cast_fu_543_p1 = esl_sext<64,10>(tmp_34_fu_538_p2.read());
}

void hand_num_nn::thread_tmp_34_fu_538_p2() {
    tmp_34_fu_538_p2 = (!tmp_33_fu_532_p2.read().is_01() || !tmp_2_cast_reg_715.read().is_01())? sc_lv<10>(): (sc_biguint<10>(tmp_33_fu_532_p2.read()) + sc_biguint<10>(tmp_2_cast_reg_715.read()));
}

void hand_num_nn::thread_tmp_3_to_int_fu_425_p1() {
    tmp_3_to_int_fu_425_p1 = reg_349.read();
}

void hand_num_nn::thread_tmp_4_fu_429_p4() {
    tmp_4_fu_429_p4 = tmp_3_to_int_fu_425_p1.read().range(30, 23);
}

void hand_num_nn::thread_tmp_5_cast_fu_388_p1() {
    tmp_5_cast_fu_388_p1 = esl_zext<8,3>(j_reg_227.read());
}

void hand_num_nn::thread_tmp_5_fu_420_p1() {
    tmp_5_fu_420_p1 = esl_zext<64,3>(j_reg_227.read());
}

void hand_num_nn::thread_tmp_8_fu_315_p0() {
    tmp_8_fu_315_p0 = tmp_neg_fu_625_p2.read();
}

void hand_num_nn::thread_tmp_cast_fu_372_p1() {
    tmp_cast_fu_372_p1 = esl_zext<8,4>(i_reg_204.read());
}

void hand_num_nn::thread_tmp_fu_367_p1() {
    tmp_fu_367_p1 = esl_zext<64,4>(i_reg_204.read());
}

void hand_num_nn::thread_tmp_neg_fu_625_p2() {
    tmp_neg_fu_625_p2 = (tmp_to_int_fu_621_p1.read() ^ ap_const_lv32_80000000);
}

void hand_num_nn::thread_tmp_to_int_fu_621_p1() {
    tmp_to_int_fu_621_p1 = reg_343.read();
}

void hand_num_nn::thread_ap_NS_fsm() {
    if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state1))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else {
            ap_NS_fsm = ap_ST_fsm_state1;
        }
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        if ((esl_seteq<1,1,1>(exitcond4_fu_355_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state22;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        if ((esl_seteq<1,1,1>(exitcond3_fu_376_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
            ap_NS_fsm = ap_ST_fsm_state14;
        } else {
            ap_NS_fsm = ap_ST_fsm_state4;
        }
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        ap_NS_fsm = ap_ST_fsm_state6;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        ap_NS_fsm = ap_ST_fsm_state7;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        ap_NS_fsm = ap_ST_fsm_state9;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        ap_NS_fsm = ap_ST_fsm_state13;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state3;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        ap_NS_fsm = ap_ST_fsm_state15;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        ap_NS_fsm = ap_ST_fsm_state20;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state21;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state2;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        if ((esl_seteq<1,1,1>(exitcond2_fu_475_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
            ap_NS_fsm = ap_ST_fsm_state42;
        } else {
            ap_NS_fsm = ap_ST_fsm_state23;
        }
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        if ((esl_seteq<1,1,1>(exitcond1_fu_496_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
            ap_NS_fsm = ap_ST_fsm_state34;
        } else {
            ap_NS_fsm = ap_ST_fsm_state24;
        }
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state35;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        if ((esl_seteq<1,1,1>(exitcond_fu_603_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read()))) {
            ap_NS_fsm = ap_ST_fsm_state53;
        } else {
            ap_NS_fsm = ap_ST_fsm_state43;
        }
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        ap_NS_fsm = ap_ST_fsm_state52;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state54;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        ap_NS_fsm = ap_ST_fsm_state60;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state70;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state70))
    {
        ap_NS_fsm = ap_ST_fsm_state71;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state71))
    {
        ap_NS_fsm = ap_ST_fsm_state72;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state72))
    {
        ap_NS_fsm = ap_ST_fsm_state73;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state73))
    {
        ap_NS_fsm = ap_ST_fsm_state74;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state74))
    {
        ap_NS_fsm = ap_ST_fsm_state75;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state75))
    {
        ap_NS_fsm = ap_ST_fsm_state76;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state76))
    {
        ap_NS_fsm = ap_ST_fsm_state77;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state77))
    {
        ap_NS_fsm = ap_ST_fsm_state78;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state78))
    {
        ap_NS_fsm = ap_ST_fsm_state79;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state79))
    {
        ap_NS_fsm = ap_ST_fsm_state80;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state80))
    {
        ap_NS_fsm = ap_ST_fsm_state81;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state81))
    {
        ap_NS_fsm = ap_ST_fsm_state82;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state82))
    {
        ap_NS_fsm = ap_ST_fsm_state83;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state83))
    {
        ap_NS_fsm = ap_ST_fsm_state84;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state84))
    {
        ap_NS_fsm = ap_ST_fsm_state85;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state85))
    {
        ap_NS_fsm = ap_ST_fsm_state86;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state86))
    {
        ap_NS_fsm = ap_ST_fsm_state87;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state87))
    {
        ap_NS_fsm = ap_ST_fsm_state88;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state88))
    {
        ap_NS_fsm = ap_ST_fsm_state89;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state89))
    {
        ap_NS_fsm = ap_ST_fsm_state90;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state90))
    {
        ap_NS_fsm = ap_ST_fsm_state91;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state91))
    {
        ap_NS_fsm = ap_ST_fsm_state92;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state92))
    {
        ap_NS_fsm = ap_ST_fsm_state93;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state93))
    {
        ap_NS_fsm = ap_ST_fsm_state94;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state94))
    {
        ap_NS_fsm = ap_ST_fsm_state95;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state95))
    {
        ap_NS_fsm = ap_ST_fsm_state96;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state96))
    {
        ap_NS_fsm = ap_ST_fsm_state97;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state97))
    {
        ap_NS_fsm = ap_ST_fsm_state98;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state98))
    {
        ap_NS_fsm = ap_ST_fsm_state99;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state99))
    {
        ap_NS_fsm = ap_ST_fsm_state100;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state100))
    {
        ap_NS_fsm = ap_ST_fsm_state101;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state101))
    {
        ap_NS_fsm = ap_ST_fsm_state102;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state102))
    {
        ap_NS_fsm = ap_ST_fsm_state103;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state103))
    {
        ap_NS_fsm = ap_ST_fsm_state104;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state104))
    {
        ap_NS_fsm = ap_ST_fsm_state105;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state105))
    {
        ap_NS_fsm = ap_ST_fsm_state106;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state106))
    {
        ap_NS_fsm = ap_ST_fsm_state107;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state107))
    {
        ap_NS_fsm = ap_ST_fsm_state108;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state108))
    {
        ap_NS_fsm = ap_ST_fsm_state109;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state109))
    {
        ap_NS_fsm = ap_ST_fsm_state110;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state110))
    {
        ap_NS_fsm = ap_ST_fsm_state111;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state111))
    {
        ap_NS_fsm = ap_ST_fsm_state112;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state112))
    {
        ap_NS_fsm = ap_ST_fsm_state113;
    }
    else if (esl_seteq<1,113,113>(ap_CS_fsm.read(), ap_ST_fsm_state113))
    {
        ap_NS_fsm = ap_ST_fsm_state1;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<113>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
void hand_num_nn::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"X_Addr_A\" :  \"" << X_Addr_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_EN_A\" :  \"" << X_EN_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_WEN_A\" :  \"" << X_WEN_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_Din_A\" :  \"" << X_Din_A.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"X_Dout_A\" :  \"" << X_Dout_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_Clk_A\" :  \"" << X_Clk_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_Rst_A\" :  \"" << X_Rst_A.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_AWVALID\" :  \"" << s_axi_CRTL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_AWREADY\" :  \"" << s_axi_CRTL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_AWADDR\" :  \"" << s_axi_CRTL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WVALID\" :  \"" << s_axi_CRTL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_WREADY\" :  \"" << s_axi_CRTL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WDATA\" :  \"" << s_axi_CRTL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WSTRB\" :  \"" << s_axi_CRTL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_ARVALID\" :  \"" << s_axi_CRTL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_ARREADY\" :  \"" << s_axi_CRTL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_ARADDR\" :  \"" << s_axi_CRTL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RVALID\" :  \"" << s_axi_CRTL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_RREADY\" :  \"" << s_axi_CRTL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RDATA\" :  \"" << s_axi_CRTL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RRESP\" :  \"" << s_axi_CRTL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_BVALID\" :  \"" << s_axi_CRTL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_BREADY\" :  \"" << s_axi_CRTL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_BRESP\" :  \"" << s_axi_CRTL_BUS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

